from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List

from core.models import Endpoint, StructuredTestCase
from services.generator import generate_tests

router = APIRouter(
    prefix="/api",
    tags=["Generator"]
)

class GenerationRequest(BaseModel):
    endpoints: List[Endpoint]
    test_count: int = 2

@router.post("/generate", response_model=List[StructuredTestCase])
async def generate_api_tests(request: GenerationRequest):
    """
    Module 8: AI Test Generator Endpoint.
    Accepts a list of selected endpoints (metadata) from the frontend,
    and returns an array of strictly typed StructuredTestCase objects 
    generated by Gemini.
    """
    try:
        if not request.endpoints:
            raise ValueError("No endpoints provided for test generation.")
            
        test_cases = generate_tests(request.endpoints, request.test_count)
        return test_cases
        
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))
